- linux/installation/mde_installer.sh
The installation script had two different typo in the lines 47 and 50 from this [PR](https://github.com/microsoft/mdatp-xplat/pull/12)
This is related to this [issue](https://github.com/microsoft/mdatp-xplat/issues/13)
> Fix installer script errors

- macos/schema/schema.json
Added:
- [Degree of parallelism for on-demand scans](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide#degree-of-parallelism-for-on-demand-scans)
- [Run a scan after definitions are updated](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide#run-a-scan-after-definitions-are-updated)
> Update schema.json to add 2 further settings

- macos/schema/schema.json
- macos/settings/data_loss_prevention/com.microsoft.wdav.mobileconfig
- macos/settings/data_loss_prevention/schema.json
- macos/settings/device_control/com.microsoft.wdav.mobileconfig
Add the DeviceControl feature to the schema.json, and the `policy` preference with links to the mdatp-devicecontrol repo containing the DC policy schema.
> Add DeviceControl preferences to schema

- macos/schema/schema.json
Added consumerExperience to the scheme.json file because it was missing. It is described in the preference documentation here: https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/mac-preferences?view=o365-worldwide#control-sign-in-to-consumer-version-of-microsoft-defender
> Update schema.json added consumerExperience

- linux/installation/mde_installer.sh
Fixes #19 
When attempting to include tags with spaces, the tag was truncated after the first space. E.g.
```
-t GROUP "Tag with spaces"
```
Would result in a tag key value of `GROUP Tag`.
This is due to the way the `${tags[@]}"` expression handles a space delimited array as passed.
The fix gathers ALL arguments after the "key" and builds a quoted string to pass to the eventual command.
> Allow Linux tagging with spaces

- linux/installation/mde_installer.sh
Add conditional for Ubuntu 22.04 under scale_version_id() to prevent scaling to version 18.04.
> Add conditional for Ubuntu 22.04

- linux/installation/mde_installer.sh
The existing Mariner flag requirement prevents the ability to deploy the MDE.Linux extension as the flag can not be explicitly set by the extension.
Removing the flag to support MDE.Linux based deployment patterns.
> Removal of Mariner Feature Flag.

- macos/mobileconfig/profiles/background_services.mobileconfig
This is a profile to prevent users from being able to disable the MDE daemons. This feature is newly added to Ventura and allows users to disable login items and daemons. 
The MDM setting has several possible ways to specify which daemons to exclude from the feature.
- BundleIdentifier : bundle ID of the app
- BundleIdentifierPrefix: prefix match of the bundle ID of the app(s)
- Label: launchd label of the app
- LabelPrefix: prefix match of the launchd label of the app(s)
- TeamIdentifier: Team identifier from code signatures
As of Ventura 13.0 release, only the LabelPrefix and TeamIdentifier is working properly.
JAMF currently doesn't support creating this setting in their UI, so it is recommended that this profile be signed before uploading to JAMF, as JAMF can modify the profile and …
> Add background services MDM profile for Ventura

- linux/LinuxMDEparser/README.MD
- linux/MDEAuditdAnalyzer/README.md
Before this change:
-  There was a minor typo in the README.md file in linux/MDEAuditdAnalyzer
After this change:
- There are no longer any typos in the mentioned file
> Fix typo in linux/MDEAuditdAnalyzer/Readme

- linux/installation/mde_installer.sh
This PR introduces two small changes.
- Send STDERR to /dev/null in the onboard_device() function. On some operating systems, the check for installed python version (which python || which python3) will produce a STDERR message that is captured in the MDE.Linux extension log when installing via VM or connected machine extension.
Example:
2022-11-29 20:32:26,649, ERROR - MDE process stdout: b'--- mde_installer.sh v0.5.9 ---\n[>] detected: mariner 2.0  (mariner)\n[>] scaled: 2.0\n[v] set package manager: yum\n[>] onboarding script: onboardingScript.tmp.py\nwhich: **no python in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)\n**[S]
- Extend sleep time between completion of onboarding_script and mdatp health check to 120 seconds. In some scenarios, the 3 second sleep is not enough time …
> Do not log STDERR and extend sleep for license chk

- macos/settings/data_loss_prevention/cloud_egress/README.md
- macos/settings/data_loss_prevention/cloud_egress/com.microsoft.wdav.mobileconfig
Add a new example for DLP settings that demonstrates how to use the `dlp/features` configuration area to enable the `DLP_browser_only_cloud_egress` feature.
> Add DLP cloud egress example settings

- linux/installation/mde_installer.sh
Currently, script checks for existing configured repos in yum via yum repolist. Currently, repolist check always gives repository as configured even when not configured. This is because of following reason: yum repolist command by default also notifies about the current state or actions of DNF in output. So, that output will be captured in grep. e.g. I issued following command in rhel 8.7, and got this result.
> sudo yum repolist nonexistingrepo | grep nonexistingrepo; echo "result=$?"
Command: yum repolist nonexistingrepo
Extra commands: ['repolist', 'nonexistingrepo']
Last metadata expiration check: 0:02:35 ago on Mon 24 Jul 2023 05:55:51 AM UTC. result=0
Added -q option in yum repolist command so that it shows just the relevant content and suppresses messages notifying about the …
> Add quiet option to yum repolist command

- linux/installation/mde_installer.sh
It is a safe practice to check command return code instead of checking standard output of a command.
> Add command result check for python instead of standard output

- linux/installation/mde_installer.sh
Commit badff9c reintroduced a shortened sleep window for validating mdatp licensing status. The proposed change brings back the extended loop that was removed for license validation. When installing mdatp on large nodes, the time it takes the mdatp service to reach a started status may take longer than the 3 seconds currently permitted.
> Resolve regression introduced in commit badff9c

- linux/installation/mde_installer.sh
This is just a very simple patch to add installer support for Alma Linux and Rocky Linux - the two clones of RHEL.
> added support for Alma Linux and Rocky Linux

- linux/installation/mde_installer.sh
In case of the mariner vm, running the installer script automatically configures the preview-repo to install mdatp, which inturn affects the mariner vm, because its starts to get preview-repo versions of other packages too while updating.
With my change it is made sure in case of mariner distro, mde installation from extras-preview repo happens only when no channel is specified in the installer script. If the installer script is run with prod channel as option then it tries to get mdatp from the extras repo.(mdatp not available here as of now, so installation expected to fail).
> updated mde_installer script in case of mariner distro

- linux/installation/mde_installer.sh
Installation using the mde_installer.sh script is failing for CentOS 8. Here's the error when trying to add repo.
Status code: 404 for https://packages.microsoft.com/config/centos/8.0/prod.repo (IP: 13.107.213.67)
Error: Configuration of repo failed
The right url is supposed to be https://packages.microsoft.com/config/centos/8/prod.repo. Thus scaled version 8.0 needs to be fixed to 8.
> Fixing installer script for CentOS-8

- macos/schema/schema.json
Extend schema.json to include scheduled scan configuration options to allow for admins to have an easier experience when creating JAMF profiles.
> Extend macOS schema to include scheduled scan configuration options

- linux/definition_downloader/xplat_offline_updates_download.ps1
- linux/definition_downloader/xplat_offline_updates_download.sh
Updating downloader script `xplat_offline_updates_download.ps1` & `xplat_offline_updates_download.sh` to allow Arm64 Linux packages to be downloaded.
Removed the check for Arm64 and Linux to skip the download for the same. Also updated the folder structure display accordingly.
> Updated offline definition downloader script to include Arm64 Linux package

- linux/installation/README.md
- linux/installation/mde_installer.sh
Issue: Current script doesn't support ARM64 architecture
Mitigation: Since MDE is now available on ARM64, we need to update the installer script to support ARM64 architecture.
Resolution: MDE released to insiders-slow channel of packages.microsoft.com. Hence this change will remove check which blocks ARM64 installation and set insiders-slow as default channel is customer wants to opt for preview version of MDE ARM64 OPT_FOR_MDE_ARM_PREVIEW=true or OPT_FOR_MDE_ARM_PREVIEW=1 else just pass insiders-slow as channel argument to install. This is only till MDE is in preview once it reaches GA it will follow same path as the x86-64 one.
Usage for ARM64:
[Recommended] sudo  ./linux/installation/mde_installer.sh --install --channel insiders-slow 
sudo OPT_FOR_MDE_ARM_PREVIEW=1 …
> Add ARM support in mde installer script

- linux/installation/mde_installer.sh
ARM is in preview hence should not be allowed unless intend to. Hence to avoid automation tool installing preview version without setting its intend. We are looking for variable defined in file /etc/mde.arm.d/mde.conf.
> Modify installation logic for ARM64

- linux/installation/mde_installer.sh
ARM check logic ignore RHEL version other than 8.0 and 9.0.
This chagne fix this issue
> Fix installer script for RHEL based distro on ARM

- linux/installation/mde_installer.sh
Now MDE for ARM Linux has reached production. Its time to udpate the installer script and remove the restriction imposed to avoid script installing MDATP on ARM through automations.
> Remove ARM preview restrictions

- linux/installation/mde_installer.sh
MDE Linux is adding support for co-existence of `fapolicyd` with MDE.
Hence, allowing an exception in conflicting applications check in installer script.
> Support for co-existence of fapolicyd with MDE,
