- linux/README.md
- linux/installation/README.md
- linux/installation/mde_installer.sh
Added an installer script and some documentation around it.
> Add installer script

- linux/LinuxMDEparser/README.ME
- linux/LinuxMDEparser/dist/README.ME
README.ME changed based on User feedback for clarity
dist folder created requested by test users --> added specific README.ME
Added Windows and MacOS release
> Changes based on Users feedback

- linux/installation/README.md
- linux/installation/mde_installer.sh
This PR
- Performs basic markdown and shell linting.
- Aligns hardware requirement to documentation, https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide
- Closes https://github.com/MicrosoftDocs/microsoft-365-docs/issues/4756
- Removes the use of `apt-get`, https://github.com/MicrosoftDocs/windowsserverdocs/pull/5203
> Shellalignment

- linux/installation/mde_installer.sh
I added a simple if condition in detect_distro() to grep /etc/os-release/ for amazon_linux:2 and then set the DISTRO='rhel' and Version=7.
> Detects AL2 and sets DISTRO=rhel and VERSION=7.

- linux/installation/mde_installer.sh
- bump version
- pass proxy parameters to RPM
> Pass proxy parameters to RPM

- linux/installation/mde_installer.sh
This PR fixes a couple typo / spelling errors.
> Fix spelling (help/error messages)

- linux/installation/mde_installer.sh
added more info to installer logs
> Update mde_installer.sh log

- linux/installation/mde_installer.sh
> Adding support for linux mint

- linux/installation/mde_installer.sh
This change is to support the [CBL-Mariner](https://en.wikipedia.org/wiki/CBL-Mariner) Linux Distribution.
> Add support for Mariner-2.0

- linux/installation/mde_installer.sh
Adding `cleanup repo`  functionality
When the script is invoked with option `-w` and a specific channel, it does the following:
1. If mdatp is installed, removes it.
2. Removes the configured mdatp repo for the specified channel.
> Clean-up repo functionality

- macos/schema/schema.json
Added the new Network protection feature (which is still in beta). Also changed the description for tamper protection since it said that this was was network protection.
> Added Network protection

- linux/diagnostic/high_cpu_parser.py
Hi @maximvelichko I've made the following changes to fix some syntax errors.
Changed groups dictionary values to list instead of set.
Added missing '[0]' to access the count.
> High cpu parser had syntax errors under 'group' section.

- macos/mobileconfig/profiles/background_services.mobileconfig
> Fix typo in background services config

- macos/schema/schema.json
- macos/settings/data_loss_prevention/schema.json
Add dlp configurations to schema.json:
* features - Enable/disable functionality
* exclusions - Per application DLP exclusions
> Add dlp configurations to schema

- linux/installation/mde_installer.sh
> add offboard function and detect arch type

- macos/schema/schema.json
When this feature is enabled Windows defender -> When this feature is enabled Defender.......
> Wording Change

- linux/installation/mde_installer.sh
Fixing these bugs:
1.  Previously, the channel was hardcoded to "insiders-fast," and during the cleanup process, no channel argument was considered, leading to the default selection of "insiders-fast." As a consequence, cleanup operations failed for all other rings except "insiders-fast."
2. Cleanup was failing if mde installation failed and there's no repo to cleanup.
3. During installation through mde_installer, we are configuring microsoft repository without checking if file already exist or not which was causing a duplicate repo file.
> fix cleanup process

- linux/definition_downloader/README.md
- linux/definition_downloader/settings.json
- linux/definition_downloader/settings.ps1
- linux/definition_downloader/xplat_offline_updates_download.ps1
- linux/definition_downloader/xplat_offline_updates_download.sh
Script is ported to support Power shell and bash variant
> adding scripts to support definition download

- linux/installation/mde_installer.sh
***Current issue***
The script mde_installer.sh requires channel as a parameter. Channel values can be either of: insiders-fast, insiders-slow, prod.
While configuring the repository based on this, assumption was that repo name for **fedora** and **sles** is ```packages-microsoft-com-$CHANNEL```. This assumption holds true for prod and insiders-fast channel. But in case of insiders-slow, the repo name is ```packages-microsoft-com-slow-prod```. So when trying to install mdatp via mde_installer.sh script for insiders-slow repo, it gives error.
***Solution***
The script now checks if channel is insiders-slow. If it is, then instead of configuring repo name as ```packages-microsoft-com-$CHANNEL```, we configure repo name to ```packages-microsoft-com-slow-prod```
> Configure correct repo name for insiders slow

- linux/definition_downloader/README.md
- linux/definition_downloader/settings.json
- linux/definition_downloader/settings.ps1
- linux/definition_downloader/xplat_offline_updates_download.ps1
- linux/definition_downloader/xplat_offline_updates_download.sh
Update the script to accept additional param to allow backing up previous bits downloaded.
Default it backs up the previous update.
> Update the script to accept additional param for backup 

- linux/definition_downloader/xplat_offline_updates_download.ps1
- linux/definition_downloader/xplat_offline_updates_download.sh
1. bump up the version
2. Download manifest file along with updates
3. use manifest file to trigger next download
> Updating the Offline Def update script

- linux/installation/mde_installer.sh
MDE Linux default mode is passive. This change provides an option to enable real time protection in installer script to override default passive mode.
> Add RTP option in Linux installer script

- linux/scheduler/README.md
- linux/scheduler/schedule_scan.py
- linux/scheduler/schedule_update.py
Submission of Python scripts to make scheduling scans and package updates easier.
> scheduler scripts for mde on linux

- linux/installation/README.md
- linux/installation/mde_installer.sh
- linux/installation/third_party_installation_playbooks/ansible.install_mde.playbook.yaml
- linux/installation/third_party_installation_playbooks/puppet.init.pp
- Added new option to pass mde version to install. 
- Also added validation for the version number.  If version number if wrong then the latest will be installed.
- There were bugs for installation in insiders-slow channel.
> Mde version selection

- linux/installation/third_party_installation_playbooks/salt.install_mdatp_manual.sls
- linux/installation/third_party_installation_playbooks/salt.install_mdatp_mde_installer.sls
Adding open source salt specific configuration files to install mdatp
> adding saltstack config mdatp installer files

- linux/installation/mde_installer.sh
1) Removed the 2 core min and 4 core pref check.
2) Removed the 4GB pref memory check.
> Adjust min req and pref min req

- .gitignore
- linux/installation/mde_installer.sh
1. Add RHEL, OL, CentOS, Debian, Ubuntu 24, SUSE 15, Mariner and Azure linux 3 support
2. Fix SUSE upgrade failure due to repo exist error
3. Fix Ubuntu 24 certificate issue
> Bring MDE ARM support for more distro

- macos/settings/data_loss_prevention/schema.json
EndpointDLP has a copy of schema.json which sets the defaultProperties to expose EDLP specific configurations.  Update this to match the latest version of schema.json (including support for EDLP exclusions).
> Update the Endpoint DLP schema.json example

- linux/installation/mde_installer.sh
Updating the mde_installer script with all the fixes and changes.
1. added function to extract mdatp health field values which handles cases with warnings
2. exit if mde not installed function created to reduce redundancy in the code.
3. added arm64 supported distros list and checks
4. a few other fixes and checks added
> Update mde_installer.sh with latest changes

- linux/installation/README.md
- linux/installation/mde_installer.sh
- multiple bug fixes
- some improvements and removing code redundancy. 
- adding more methods
- updated the version due to multiple bug fixes and improvements
> Bug Fixes and Improvements

- linux/installation/mde_installer.sh
- updated the affective distro and scaled version for amazon linux distros. this will point to the correct pmc location for repo configuration. refer the updated link [here](https://learn.microsoft.com/en-us/defender-endpoint/linux-install-manually?view=o365-worldwide#rhel-and-variants-centos-fedora-oracle-linux-amazon-linux-2-rocky-and-alma)
- updated the version to 0.8.1
> Update amazon repo link

- linux/installation/mde_installer.sh
Removed falcon-sensor from list of conflicting apps check. This will allow the product to work side-by-side with CRWD.
> Remove check for CRWD conflicting app

- linux/installation/mde_installer.sh
Added functionality to validate custom path installation version for MDE.
> Implement custom path installation version validation

- macos/upgrade_from_2506_helper/README.md
> Update download link for upgrade_from_25062_helper in README.md

- macos/schema/schema.json
Add Offline security intelligence updates feature settings to schema.json.
For more information see [documentation](https://learn.microsoft.com/en-us/defender-endpoint/mac-support-offline-security-intelligence-update).
> Update schema.json: add offlineDefinitionUpdate
